### PR TITLE
subscriptions status unit test

### PR DESCRIPTION
**Pull request by Hongjiequ**
#  #

## 🗣 Description ##
This merge request is for the unit test of Con-PCA Overview -> Subscriptions Status tab

## 💭 Motivation and context ##
Please see: https://cset.atlassian.net/jira/software/c/projects/CPD/boards/20?modal=detail&selectedIssue=CPD-974

## 🧪 Testing ##
It passed in my local

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by itsmostafa — APPROVED** [review]

**Comment by jsf9k** [comment]
@Hongjiequ, please fill out the PR description template!

**Comment by Hongjiequ** [comment]
@jsf9k, it's done. Thanks

**Comment by jsf9k** [comment]
@Hongjiequ - you checked some checkboxes, but the other sections (Description, Testing, etc.) remain empty.

[Here](https://github.com/cisagov/kali-packer/pull/121) is a recent example, if you're unsure what goes in each section.

**Comment by dav3r** [comment]
Additionally, if any checkboxes don't apply to this PR, they can be deleted.  Ideally, every PR should have all (remaining) checkboxes checked when the PR has been completed.

**Comment by Hongjiequ** [comment]
@jsf9k and @dav3r, I updated according to your suggestions. Thanks

**Pull request merged**
